### ISSUE TITLE
Infinite loop on login

### ISSUE THREAD

**Issue by gbenga** [Garrett1Tolbert/tap#3]
When I sign in using Google, there is a constant loop of updating the user
<img width="572" alt="Screenshot 2020-11-18 at 21 33 05" src="https://user-images.githubusercontent.com/57733903/99590735-a8224580-29e5-11eb-94df-1159d82d8c98.png">

**Comment by gt-codes** [comment]
@gbenga I'm not getting that error, the error that I'm seeing is

`FirebaseError: Missing or insufficient permissions.`

**UPDATE**
I fixed this minor issue 👆🏿. Someone changed the database rules

**Comment by gbenga** [comment]
@Garrett1Tolbert All good now thanks.
